# script which takes the coefficirent generated by estimate.R
# and obtains Cpc for the predefined positions
# 
# required: ./Coefficients/*.csv with the coefficients
library(data.table)

# file name where to save final results
fid = 'curves_BE' # or NL

# initialize containers, we are only interested in positions 
# ups to 4 with a delta of 0.1
position = seq(1, 4, 0.1)
curve_Desktop = rep(0, length(position))
curve_Tablet = rep(0, length(position))
curve_Mobile = rep(0, length(position))

# variables to track number of models that couldn't be fitted
counter_nonNaN_Tablet = 0
counter_nonNaN_Mobile = 0
counter_nonNaN_Desktop = 0

counter_all_Tablet = 0
counter_all_Mobile = 0
counter_all_Desktop = 0

files = list.files(path="./Coefficients/")
n_files = length(files) - 1

for (i in 0:n_files){
  
  coeffs = fread(paste0('./Coefficients/chunk_', i, '.csv'))
  coeffs = coeffs[coeffs$AdGroupId %in% shortlist_adgroup, ]
  
  if(dim(coeffs)[1] > 0){ # control empty files
    
    for(j in 1:dim(coeffs)[1]){ # 
      
      if (!(is.na(coeffs$log_AvpPos[j]))){ # avoid NaNs
        
        # aggregate curves and track the counter per device
        if(coeffs$device[j] == 'Desktop'){
          curve_Desktop = curve_Desktop + as.numeric(coeffs$log_AvpPos[j]) * log(position) + as.numeric(coeffs$Intercept[j])
          counter_nonNaN_Desktop = counter_nonNaN_Desktop + 1
        }
        
        if(coeffs$device[j] == 'Tablet'){
          curve_Tablet = curve_Tablet + as.numeric(coeffs$log_AvpPos[j]) * log(position) + as.numeric(coeffs$Intercept[j])
          counter_nonNaN_Tablet = counter_nonNaN_Tablet + 1
        }
        
        if(coeffs$device[j] == 'Mobile'){
          curve_Mobile = curve_Mobile + as.numeric(coeffs$log_AvpPos[j]) * log(position) + as.numeric(coeffs$Intercept[j])
          counter_nonNaN_Mobile = counter_nonNaN_Mobile + 1
        }
        
      }
      
      if(coeffs$device[j] == 'Desktop'){
        counter_all_Desktop = counter_all_Desktop + 1
      }
      
      if(coeffs$device[j] == 'Mobile'){
        counter_all_Mobile = counter_all_Mobile + 1
      }
      
      if(coeffs$device[j] == 'Tablet'){
        counter_all_Tablet = counter_all_Tablet + 1
      }
      
      
    }
  }

  print(paste0(i, '/', n_files))
}

# average
curves= data.frame(Position = position,
                   Desktop = curve_Desktop / counter_nonNaN_Desktop,
                   Tablet = curve_Tablet / counter_nonNaN_Tablet,
                   Mobile = curve_Mobile / counter_nonNaN_Mobile)

write.csv(curves, fid)
